### ISSUE TITLE
DONATE PAGE - custom amount field

### ISSUE THREAD

**Issue by bhalligan** [jakewelchert/mtuck#10]
In the custom amount field on the donation form, the dollar sign is obstructing the dollar amount. 

![screen shot 2017-03-10 at 4 07 33 pm](https://cloud.githubusercontent.com/assets/1952997/23815039/afc5e0ba-05ab-11e7-8120-a1fff81b9745.png)

**Comment by jakewelchert** [comment]
Resolved.
