### ISSUE TITLE
LEGAL LANGUAGE - found at bottom of site

### ISSUE THREAD

**Issue by bhalligan** [jakewelchert/mtuck#11]
Paid for by Marshall Tuck for Superintendent of Public Instruction 2018

**Comment by lfleischer** [comment]
@bhalligan does it need to be in a box in the footer?

**Comment by bhalligan** [comment]
Yes, I think we should put this in a box at the footer.

**Comment by bhalligan** [comment]
Also can we remove "Privacy Policy" link (both the copy and the hyperlink) next to ©2017 Marshall Tuck on the bottom?

**Comment by jakewelchert** [comment]
Resolved. Removed Privacy Policy link and replaced it with email since they requested adding it to the footer.
