### ISSUE TITLE
HOMEPAGE COPY 

### ISSUE THREAD

**Issue by bhalligan** [jakewelchert/mtuck#14]
Campaign wants this:

**Headline: Renew the promise of public education. 

Body:  “I’m running for State Superintendent because California has settled for mediocrity for too long. No more excuses. No more empty promises. It’s time for bold action to renew the promise of public schools, and finally give all children the education they deserve.” – Marshall Tuck**

But I'm thinking that might be too hard to read with the photo. What if we change the headline to "Renew the promise of public education." but then for body copy have it read "Marshall Tuck for State Superintendent"

**Comment by jakewelchert** [comment]
@bhalligan A bit confused here...

There's way too much copy for this. I can try the second option but will take a bit more time due to there needing to be some sizing changes.

**Comment by bhalligan** [comment]
Okay, lovely. Campaign could be fine with just scrapping the quote and going with "Renew the promise of public education" as the header here. 

If we think "Marshall Tuck for State Superintendent" fits underneath it; let's do it. If not, just the headline swap.

**Comment by jakewelchert** [comment]
Updated copy is in place. I'll need to do some more testing for different browser dimensions. 

Will do Sunday.

**Comment by jakewelchert** [comment]
Resolved.
