### ISSUE TITLE
MOBILE VERSIONS - homepage and get involved

### ISSUE THREAD

**Issue by bhalligan** [jakewelchert/mtuck#16]
On the homepage: campaign would like the mobile versions to not cut off Marshall's face/body at the midpoint. Is there a way we can center the zoom a but more on him and leave out the classroom?

On the get involved page: on my browser this is handled better, but on my phone, the picture is extremely zoomed just on Marshall's ear. Can we handle this photo more like we handle the homepage? Thank you! 

![img_8298](https://cloud.githubusercontent.com/assets/1952997/23826574/3082a748-0664-11e7-98fb-603cf127d6a7.PNG)

(Generally, the campaign thinks we're handling mobile wrong. They think the image should just get smaller instead of zooming in on a part -- like the homepage of https://www.ericgarcetti.com. I told them I think we did this for a few reasons, and that we'd reevaluate after launch, but that I would address the two things they're asking about specifically.)

**Comment by jakewelchert** [comment]
(Very lighthearted) Tell them this is what happens with limited time for development and testing : )

I agree here though, these need to be treated in a better way. I can focus on improving these pages tomorrow. The big thing to remember is that they specifically wanted large background photos, which look okay on desktop, but can become an issue with mobile. The site they sent will help me with direction.

With the photos, can we get them to narrow those down to only a few and send direct links? The photo on the Get Involved page shouldn't have him focused in the middle.

Thanks!

**Comment by jakewelchert** [comment]
Edited made to the Get Involved page. Feel free to review. Was there an image change here too?

**Comment by bhalligan** [comment]
Thanks. This is the one they are hoping to slide down a bit so that we don't slice off the heads. Doable? Thanks

**Comment by bhalligan** [comment]
Sorry. Above is about Get Involved. 

They are also hoping for this same edit to the Homepage. On mobile, we slice half of Marshall's body. They'd rather see the full body and not as much of the classroom.

**Comment by jakewelchert** [comment]
Resolved. Updated for both pages.

**Comment by bhalligan** [comment]
Homepage looks awesome. Thanks for chasing this one down.
