### ISSUE TITLE
DONATION PAGE - adding max contribution

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/mtuck#18]
How should this be treated? Is it a line of copy or button?

**Comment by bhalligan** [comment]
I think we actually can set these in NGP. Checking it out. 

Campaign's request: "Let's make sure the $7,300 button is there- or, at the very least, directly under/on top of the buttons there is a note alerting them that there is $7,300 per person per election limit-- we definitely don't want people thinking $2,500 is the max."

**Comment by jakewelchert** [comment]
Go ahead and make all of your changes and then If it needs style updates I can make. Thanks!

**Comment by bhalligan** [comment]
K, just pushed that change.

**Comment by jakewelchert** [comment]
Looks fine to me. Should we change the Contribute button to say Donate?

![screen shot 2017-03-12 at 1 58 37 pm](https://cloud.githubusercontent.com/assets/3301072/23834901/18710014-072c-11e7-8d2c-af2ee3916cf2.png)

**Comment by bhalligan** [comment]
Oh, yes, I like that. (Is that a change I make, or you make? Looking in NGP.)

**Comment by jakewelchert** [comment]
It's in NGP. On the build page, I believe.

**Comment by bhalligan** [comment]
K, did it! Might want to add in recurring contributions here. Okay for me to try that, and if it messes up our page at all, I'll just undo it?

**Comment by jakewelchert** [comment]
Sounds good.

**Comment by jakewelchert** [comment]
Were there any additional issues here?

**Comment by lfleischer** [comment]
@bhalligan if not, let's close this out. Go team!

**Comment by jakewelchert** [comment]
Resolved.
