### ISSUE TITLE
PHOTO SWAP - Volunteer + Thank you for signing up pages

### ISSUE THREAD

**Issue by bhalligan** [jakewelchert/mtuck#20]
[**Volunteer page**](https://marshalltuck.com/volunteer/) 
[Picture 243](https://www.dropbox.com/sh/6zm18k3msz4hp68/AAC0gu9thr1SJAJHHyJIcQmHa/Playground/Tuck%20and%20Moms?dl=0&preview=meeno-Marshall+Tuck+2017+-243_1.jpg)

[Thank you for signing up](https://marshalltuck.com/thank-you-donate/)
[Picture 385](https://www.dropbox.com/sh/6zm18k3msz4hp68/AADJaO40w_SMwGYisr8Y9zAGa/Elementary%20School%20Classroom/Tuck%20and%20Kids/Playing?dl=0&preview=meeno-Marshall+Tuck+2017+-385_1.jpg)

**Comment by jakewelchert** [comment]
Resolved. Photos are updated.

**Comment by bhalligan** [comment]
Hey, not seeing the photo update on the Thank you for signing up page. 

That page is: https://marshalltuck.com/thank-you-donate/

**Comment by jakewelchert** [comment]
Image was added here: https://marshalltuck.com/thank-you/ <https://marshalltuck.com/thank-you/>

Now also added here: https://marshalltuck.com/thank-you-donate/ <https://marshalltuck.com/thank-you-donate/>
_______

Jake Welchert

e - jakewelchert@gmail.com
p - 402-980-5368
