### ISSUE TITLE
HOMEPAGE LOGO - desktop 

### ISSUE THREAD

**Issue by bhalligan** [jakewelchert/mtuck#21]
I'm seeing a white square behind the boy's head on the homepage. 

I'm using Chrome Version 56.

![screen shot 2017-03-12 at 1 23 46 pm](https://cloud.githubusercontent.com/assets/1952997/23834597/2cd0a1d6-0727-11e7-8717-0b576b196cf9.png)

**Comment by jakewelchert** [comment]
Resolved. Edited image file.
