### ISSUE TITLE
ABOUT MARSHALL - small copy change

### ISSUE THREAD

**Issue by bhalligan** [jakewelchert/mtuck#22]
"Partnership launched" should read "The Partnership launched"

**Comment by jakewelchert** [comment]
Looks like Partnership is the name so should it be changed to "The Partnership" in the paragraph above too?

**Comment by bhalligan** [comment]
Yes, thank you.

**Comment by bhalligan** [comment]
Not seeing this change in latest version. To clarify: We need to add "The" in front of this sentence in the fourth paragraph: "Partnership launched the innovative Parent College, creating a national model for getting parents more involved in their kids’ education."
