### ISSUE TITLE
HOMEPAGE - "Why I'm Running" copy change

### ISSUE THREAD

**Issue by bhalligan** [jakewelchert/mtuck#25]
Headline should read "Students Above All" 
And copy should be: 

Marshall will put students ahead of politics and take bold action to renew the promise of public education in California schools.

Tuck has led both public charter and traditional public school systems in poor neighborhoods, where he worked with parents and teachers to turn around failing schools and improve student achievement.

Together, we can give all of our children the schools they deserve.

[Button]

**Comment by jakewelchert** [comment]
Resolved.

**Comment by bhalligan** [comment]
Need to update the middle paragraph of this. Clean copy here, though the middle graph is the only thing that is changing.

Marshall will put students ahead of politics and take bold action to renew the promise of public education in California schools. 

Tuck has worked with parents and teachers to turn around failing schools and open new, high-quality public charter schools in some of LA's poorest neighborhoods.

Together, we can give all of our children the schools they deserve.

**Comment by jakewelchert** [comment]
Resolved.
