### ISSUE TITLE
FB SHARE BUTTONS - Across site

### ISSUE THREAD

**Issue by bhalligan** [jakewelchert/mtuck#26]
Part I: When I click on the Facebook share button underneath "Why I'm Running" (soon to be "Students Above All") section of homepage, I get a 401 Authorization image/error as the post. Is that becuase Facebook is trying to pull from the password protected homepage? Is there a way we can see what image it's pulling so that we can control? Campaign would like the logo, if possible at this stage. 

The same thing happens when I click it on "Get Involved," on the "Students Above All" full page, and on the "About Marshall" full page. 

Part II: Am I right to remember that FB share doesn't allow you to input text for users? Like they will need to put in their own copy for the share post, right?

**Comment by jakewelchert** [comment]
Part 1: This functionality should be fine once we remove the password protection. We can check right when we switch over.

Part 2: Nope, no filled in info. It's more of like a pre-styled image, block of text, and title.

**Comment by lfleischer** [comment]
Looking good to me. Here's what I see on FB debugger:

![image](https://cloud.githubusercontent.com/assets/11965767/23857835/ff37fd06-07d4-11e7-8359-427e4e9e9449.png)

**Comment by jakewelchert** [comment]
Resolved.
