### ISSUE TITLE
SIGNUP FORM - copy 

### ISSUE THREAD

**Issue by bhalligan** [jakewelchert/mtuck#27]
Sorry I neglected this page: https://marshalltuck.com/signup and thanks for jumping on it.

**Part 1: signup form**
It's currently pulling from the same signup form that we're using for the volunteer page, so the auto-responder says thanks for volunteering. Can we use NGP form 83750? It's called "module signup."

**Part II: Here is the copy**
Header: Marshall Tuck for State Superintendent 

Body: Join us and help renew the promise of public education. 

Email + ZIP

**Comment by jakewelchert** [comment]
This will have to be another signup page created in NGP. 83750 is styled like the modules on the homepage, so the layout is going to be pretty funky.

**Comment by bhalligan** [comment]
Roger. I'll clone the one we like, change the autoresponder, and get you the page ID. 

**COPY**
Header: Join the team!

Body: Marshall knows from experience that we can dramatically improve public schools -- as long as parents, teachers, and all Californians come together to demand better.

Join us and help renew the promise of public education.

**Comment by jakewelchert** [comment]
Sounds great! One final thing that was discussed from yesterday on the forms...the volunteer should be name and email. You can do this in NGP VAN. Can you change while you're setting the other page up?

**Comment by bhalligan** [comment]
New form ID is 83828

**Comment by jakewelchert** [comment]
Resolved.

**Comment by jakewelchert** [comment]
Also updated the volunteer email signup. Now pulls First Name, Last Name, and Email. Auto-responder looks good but feel free to check.
