### ISSUE TITLE
GOOGLE ANALYTICS & GOOGLE TAG - Add to WordPress

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/mtuck#4]
Still need analytics key

**Comment by bhalligan** [comment]
UA-93585801-1

**Website Tracking**
This is the Universal Analytics tracking code for this property.
To get all the benefits of Universal Analytics for this property, copy and paste this code into every webpage you want to track.

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-93585801-1', 'auto');
  ga('send', 'pageview');

</script>


**PHP Implementation**
Use the code above to create a file named "analyticstracking.php", and include the file on each PHP template page. Add the following line to each template page immediately after the opening <body> tag:
<?php include_once("analyticstracking.php") ?>

**Comment by jakewelchert** [comment]
Resolved.
