### ISSUE TITLE
NAVIGATION - Update with new logo

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/mtuck#5]
Still need logo from client

**Comment by jakewelchert** [comment]
New logo is in place. Only spot where readability is an issue is on the homepage. Any thoughts on how we could treat it?

**Comment by lfleischer** [comment]
What about putting his name in white on the homepage version? Otherwise I think it works.

![image](https://cloud.githubusercontent.com/assets/11965767/23823480/aaa8a794-0631-11e7-8220-ac154861afe0.png)

**Comment by jakewelchert** [comment]
Resolved. Homepage version in white text.
