### ISSUE TITLE
SOCIAL SHARE - Add functionality and correct language

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/mtuck#6]

**Comment by jakewelchert** [comment]
Twitter share copy
I support @MarshallTuck for State Superintendent because he’s the best choice for students. Join me: [LINK] #TeamTuck

Facebook share copy
Headline: Marshall Tuck for State Superintendent
Description: The best choice for students.

Email share text
Subject: The candidate I support for State Superintendent
Body copy:
Hey,

I wanted to share this with you -- Marshall Tuck is running for California’s State Superintendent of Public Instruction, and I’m excited to support him. He’s got the experience and the vision to dramatically improve California’s public schools.

Check out his site for more information, and join me to get involved:

www.marshalltuck.com

**Comment by bhalligan** [comment]
Marshall is using Internet Explorer and is reporting: Email (on the get involved) isn't working on my explorer – it took me to google instead of gmail.

**Comment by bhalligan** [comment]
Is this issue also tracking the share buttons on the "About Marshall" and "Students Above All" pages? Right now they send you back to the top of the page.

**Comment by jakewelchert** [comment]
With the Email/Internet Explorer issue...this is something that is a thing with IE. Most of the time it has to deal with the users local email setup...so it could be on his end.

Also, for share buttons on the "About Marshall" and "Students Above All" pages...I'm working on that now.

**Comment by jakewelchert** [comment]
Resolved. Will need to test more when the site password is taken off since it currently gives an authorization error on page shares.
