### ISSUE TITLE
USER FLOW - Clicking "Volunteer" from Get Involved page

### ISSUE THREAD

**Issue by bhalligan** [jakewelchert/mtuck#7]
On the user flow, I think the only note is the "volunteer" experience on the "Get Involved" page. 

Clicking on the "Volunteer" button from [this Get Involved page](http://tuck270.wpengine.com/get-involved/) currently goes to the "Thank you for signing up" page. Think this needs to go to a place where the user can signify they can do more -- they talked through this on Friday but apologies for not being explicit about it since then. That page can just be a version of the signup form with this copy: 

HEADER: Sign up to volunteer with the campaign

COPY: Our work to renew the promise of a great public education must begin now, and it must include us all. From reaching out to your neighbors, to sharing the great work you are already doing in your community to support kids, we need you on this team. Sign up, and we will be in touch about the ways we can work together to finally give all children the education they deserve. 

FIELDS: ZIP/EMAIL

**Comment by jakewelchert** [comment]
@bhalligan Sounds good! I'm glad you noticed this because I had a question about it and forgot to ask. I believe you can actually set up a Volunteer page through NGP VAN. Is this something that eventually wants to be done, or is the email signup you have above still okay?

**Comment by jakewelchert** [comment]
This is resolved. Volunteer button on Get Involved page now points to http://tuck270.wpengine.com/volunteer/
